# Generated by Django 3.2.4 on 2021-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_gstglobal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
