# Generated by Django 3.2.4 on 2021-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_gstglobal_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupedproduct',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variableproduct',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
