# Generated by Django 3.2.4 on 2021-10-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211010_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupedproduct',
            name='quantity',
        ),
    ]
