# Generated by Django 3.2.4 on 2021-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_groupedproduct_gsm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponGlobaladd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingExpressGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiping_city', models.CharField(blank=True, max_length=200, null=True)),
                ('shiping_weight', models.FloatField(blank=True, null=True)),
                ('shiping_charges', models.FloatField(blank=True, null=True)),
                ('air_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPlusGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiping_city', models.CharField(blank=True, max_length=200, null=True)),
                ('shiping_weight', models.FloatField(blank=True, null=True)),
                ('shiping_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
