# Generated by Django 3.2.4 on 2021-10-20 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_couponglobaladd_coupon_applied_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProdcuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouped_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.groupedproduct')),
                ('simple_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.simpleproduct')),
                ('variable_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.variableproductattributes')),
            ],
        ),
    ]
