# Generated by Django 3.2.4 on 2021-10-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_allprodcuts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_Sellers_grouped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.groupedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Best_Sellers_simple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.simpleproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Best_Sellers_variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.variableproductattributes')),
            ],
        ),
        migrations.AlterField(
            model_name='newlaunches',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.variableproduct'),
        ),
        migrations.DeleteModel(
            name='Best_Sellers',
        ),
    ]
