# Generated by Django 3.2.4 on 2021-10-10 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('color', models.CharField(max_length=25, null=True)),
                ('size', models.CharField(max_length=30, null=True)),
                ('costprice', models.FloatField()),
                ('type', models.CharField(max_length=50, null=True)),
                ('timesmap', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderitem', models.TextField(default=False)),
                ('subtotal', models.IntegerField(null=True)),
                ('gst', models.FloatField(null=True)),
                ('packaging', models.IntegerField(null=True)),
                ('grandtotal', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Printunlock.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Ordercart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printunlock.cart')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printunlock.guest')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printunlock.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Printunlock.guest')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printunlock.cart')),
            ],
        ),
        migrations.CreateModel(
            name='cartFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
                ('cartitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Printunlock.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Printunlock.guest'),
        ),
    ]
