# Generated by Django 3.2.4 on 2021-10-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Printunlock', '0002_cartgrouped_cartsimple_cartvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartGroupedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
                ('cartitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Printunlock.cartgrouped')),
            ],
        ),
        migrations.CreateModel(
            name='cartSimleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
            ],
        ),
        migrations.CreateModel(
            name='cartVariableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
                ('cartitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Printunlock.cartvariable')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartfile',
            name='cartitem',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='items',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='order',
        ),
        migrations.AddField(
            model_name='cartsimple',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartsimple',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='cartFile',
        ),
        migrations.DeleteModel(
            name='Cartitem',
        ),
        migrations.DeleteModel(
            name='Ordercart',
        ),
        migrations.AddField(
            model_name='cartsimlefile',
            name='cartitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Printunlock.cartsimple'),
        ),
    ]
