# Generated by Django 3.2.4 on 2021-10-11 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211010_1655'),
        ('Printunlock', '0004_auto_20211010_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartgrouped',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AlterField(
            model_name='cartsimple',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AlterField(
            model_name='cartvariable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.DeleteModel(
            name='guest',
        ),
    ]
