# Generated by Django 3.2.4 on 2021-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printunlock', '0006_auto_20211013_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfinal',
            old_name='coupon_Applied',
            new_name='coupon_Applied_type',
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='coupon_applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='coupon_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='order_Status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfinal',
            name='product_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
